### PR TITLE
LANG: Fix indefinitely rebuilding language settings menu

### LINKED ISSUE #705: Game crash on language settings
## Disclaimer

If you are missing the following information your issue will be closed!

- "Your version of TTT2" : Lastest version
- "Describe the bug"

Also please make sure to read the [FAQ](https://docs.ttt2.neoxult.de/troubleshooting) and [existing issues](https://github.com/TTT-2/TTT2/issues?q=is%3Aissue) first!

## Your version of TTT2 (mandatory)

(v0.7.4b) lastest version

## Video

https://streamable.com/6w9cni

## Describe the bug (mandatory)

When i go to the language settings  i got an error and my game crash, sometimes he didnt crash and the HUD refresh and i got : This translation is {coverage}% complete with the english language taken as a default reference. and after that he instantly crash

## Context (please provide as much as you can)

I only have TTT2 installed on a local server

## Additional context

Screen with the lua error 
Capture

### PR DESCRIPTION
**Pull request by Histalek**
Prevent the language menu from rebuilding indefinitely. fixes #705

### CODE REVIEW

**Review by saibotk — APPROVED** [review]
Thank you very much :rocket:

File: gamemodes/terrortown/gamemode/shared/sh_lang.lua [hunk 1]
```diff
@@ -112,7 +112,7 @@ if SERVER then
 
 	---
 	-- @realm server
-	local cv_ttt_lang_serverdefault = CreateConVar("ttt_lang_serverdefault", "english", FCVAR_ARCHIVE)
+	local cv_ttt_lang_serverdefault = CreateConVar("ttt_lang_serverdefault", "en", FCVAR_ARCHIVE)
```
Comment (TimGoll) [inline gamemodes/terrortown/gamemode/shared/sh_lang.lua:115]: do we have to add a coverter here so the convar with "english" is changed to "en"?

Comment (TimGoll) [reply gamemodes/terrortown/gamemode/shared/sh_lang.lua:115]: As discussed on discord this isn't a problem at all.

**Review by TimGoll — APPROVED** [review]
