### PR TITLE
Fix up issues related to +use, doors, buttons, and such

### LINKED ISSUE #1626: Error in relation with usable map entities
## Your version of TTT2 (mandatory)

- TTT2 v0.14.0b Workshop version from Steam

## Describe the bug (mandatory)

This error only occured on one map. I don't remember on which one but it occured if you try to interact with something or something in that direction. Maybe because of weird usable map entities like levers or chests which are not correct placed on the map or something like that.

## To reproduce

Steps to reproduce the behaviour:

1. Go onto some maps (maybe Minecraft maps)
2. Interact with usable entities like levers, chests, ...
3. See error

## Expected behaviour

This error shouldn't happen.

## Context (please provide as much as you can)

- Collection link of your Server: https://steamcommunity.com/sharedfiles/filedetails/?id=1822673195
- Server error in the server console:
```
[TTT2 (Base) - v0.14.0b] gamemodes/terrortown/gamemode/server/sv_entity.lua:88: Tried to use a NULL entity!
  1. ObjectCaps - [C]:-1
   2. IsUsableEntity - gamemodes/terrortown/gamemode/server/sv_entity.lua:88
    3. func - gamemodes/terrortown/gamemode/server/sv_player.lua:533
     4. unknown - lua/includes/extensions/net.lua:38
```

### LINKED ISSUE #1633: Buttons: Solid buttons can't be passed
TTT2 v0.14.0

On the simpsons map buttons are used instead of doors. Making buttons traceable changed it so that a player can no longer walk through them: https://discord.com/channels/442107660955942932/467653559408656384/1288523369783885875

### LINKED ISSUE #1691: Doors with the flag "Ignore player +USE" can be opened when pressing Use key
## Your version of TTT2 (mandatory)

- Workshop version (0.14.0b)

## Video

https://www.youtube.com/watch?v=z2ynpoBHs9I
(I realize there's no sound, you'll have to trust that I was spamming E in the first part when showing what's supposed to happen in vanilla TTT)

## Describe the bug (mandatory)

While running TTT2 the flag "Ignore player +USE" on prop_door_rotating (I'm unsure if other doors are affected) seems to be ignored. The player can still use their Use/interact key on that door and open it. The same thing doesn't seem to happen on vanilla TTT.

## To reproduce

Steps to reproduce the behaviour:

1. Go to ttt_policedepartment_betav6 (https://steamcommunity.com/sharedfiles/filedetails/?id=294631002 only example I have)
2. Navigate to the Traitor room at the very back of the building, where the jail cells and Traitor tester are located
3. Walk up to either door for the Traitor room and press E

## Expected behaviour

The door to not open on use.

## Context (please provide as much as you can)

- Collection link of your Server: Not applicable as this still happened with all addons (Aside from TTT2 it's just Pointshop, ULX, TTT Weapon Placer, and some maps anyway) I had installed on my client unsubscribed and uninstalled when testing in Singleplayer.
- No errors seemed to be thrown.
- No add-ons, I removed _everything_. Tried in vanilla TTT and then with _only_ TTT2 installed
- Screenshots: How I have the doors set in Hammer
https://i.imgur.com/5Y2OPJw.png
https://i.imgur.com/yZamSx6.png

## Additional context

Admittedly, I'm unsure if  "Ignore player +USE" is the issue here or if it's just because I don't have the doors locked in the first place. Either way, not _supposed_ to be able to open them like that.

### LINKED ISSUE #1775: +use on brush doors doesn't open them
1. download example map: https://steamcommunity.com/sharedfiles/filedetails/?id=3183036324

2. load map in ttt2

3. try to press E on any door (rotating or sliding doors)

4. it doesn't work

seems like a pretty severe issue

is there any reason why ttt2 needs to mess with the default +use behaviour on doors in the first place? seems like it just leads to a lot of breakage especially since it appears these changes barely get tested (if at all)

seems to be related to #1691 (from 3 months ago)

### PR DESCRIPTION
**Pull request by wgetJane**
fixes #1775
fixes #1691
fixes #1633
fixes #1626

### CODE REVIEW

**Comment by wgetJane** [comment]
this should be ok for testing now, i've tested it on a bunch of maps and it seems to work like it does in ttt (the main goal of this pr is to restore parity with ttt's +use behaviour with map entities)

gonna mention @Crashington since they seem to have had issues with ttt2 stuff in their maps as well, pls let me know if those issues are fixed with this pr

also i'm gonna be restore crowbar unlocking/opening behaviour to be in line with base ttt, then i'll open this pr after that

**Comment by TimGoll** [comment]
I will try to see if this breaks any things that I implemented with external addons

**Comment by Crashington** [comment]
can confirm from my end that the pr fixes the two issues i found (#1 doors not being openable when the door entity origin is too far away from the door brush the player pressed use on. #2 func_rotating being paused/started by +use)

**Comment by TimGoll** [comment]
Seems like your changes broke this addon from me: https://steamcommunity.com/sharedfiles/filedetails/?l=indonesian&id=3335175627

other than that everything seems to work fine right now

**Comment by TimGoll** [comment]
Ah, another issue: When having a marker vision entity in LOS and looking at it, hitting E not only opens its UI, but also triggers the button:

image

This is something that should not happen

**Comment by wgetJane** [comment]
> Seems like your changes broke this addon from me: https://steamcommunity.com/sharedfiles/filedetails/?l=indonesian&id=3335175627
> 
> other than that everything seems to work fine right now

i'll check later, what's broken specifically?

**Comment by TimGoll** [comment]
> > Seems like your changes broke this addon from me: https://steamcommunity.com/sharedfiles/filedetails/?l=indonesian&id=3335175627
> > other than that everything seems to work fine right now
> 
> i'll check later, what's broken specifically?

The addon is able to overwrite the name and description for buttons - that seems to no longer work.

Well, maybe it was on me. I just notived I have multiple version of this MC map. Maybe I chose the wrong one. I will test again!

**Comment by wgetJane** [comment]
> Ah, another issue: When having a marker vision entity in LOS and looking at it, hitting E not only opens its UI, but also triggers the button:
> 
> This is something that should not happen, markervision elements, same as traitor buttons, should have priotiy over in world entities

oh right i forgot, ttt is supposed to "cancel" your actual +use if you're pointing at a "special use" entity like corpses and traitor buttons and such

**Comment by TimGoll** [comment]
Confirmed on `ttt_elevatorandstairs` that it is not working:

image
image

Not even the admin-info is working:

image

This should show info about the button (like its ID etc)

Here's the relevant code: https://github.com/TTT-2/ttt2-button_info/blob/main/lua/terrortown/autorun/client/cl_buttoninfo_tid.lua#L8-L31

If the ent is valid on the server and the client, then this should work

**Comment by wgetJane** [comment]
@TimGoll seems to work fine for me
image

**Comment by TimGoll** [comment]
@wgetJane That is so weird, because it still doesn't work for me

**Comment by TimGoll** [comment]
@wgetJane you're right, oof. Somehow I enabled minimal mode for targetID:

image

works now. So consider this resolved

**Comment by TimGoll** [comment]
Your changes also fix #1627

**Review by EntranceJew — APPROVED** [review]

File: gamemodes/terrortown/entities/weapons/weapon_zm_improvised.lua [hunk 1]
```diff
@@ -108,7 +108,7 @@ function SWEP:OpenEnt(hitEnt)
                 hitEnt:Fire("Unlock", nil, 0)
             end
 
-            if unlock or hitEnt:HasSpawnFlags(SF_NPC_LONG_RANGE) then -- Long Visibility/Shoot
+            if unlock or hitEnt:HasSpawnFlags(256) then
```
Comment (TimGoll) [inline gamemodes/terrortown/entities/weapons/weapon_zm_improvised.lua:111]: Is there a reason you used this magic number instead of a spawn flag?

**Review by TimGoll — APPROVED** [review]
Thank you so much for looking into this issue. That looks really good to me. Besides the one question, could you add to your changelog that you also fixed the car usage?

File: gamemodes/terrortown/entities/weapons/weapon_zm_improvised.lua (hunk 1 above)
Comment (wgetJane) [reply gamemodes/terrortown/entities/weapons/weapon_zm_improvised.lua:111]: the old one is intended for npcs, it makes zero sense to use it for door entities

Comment (TimGoll) [reply gamemodes/terrortown/entities/weapons/weapon_zm_improvised.lua]: ah, yes, that makes sense!

Comment (TimGoll) [reply gamemodes/terrortown/entities/weapons/weapon_zm_improvised.lua]: And I was about to suggest a comment, but you already did it. Thank you

**Comment by Crashington** [comment]
it is with a heavy heart that i must report that the most recent update seems to have not fixed everything it should have.
https://steamcommunity.com/sharedfiles/filedetails/?id=1293781407
on this version of waterworld the button inside the soda machien that is supposed to teleport you does not work
also, it seems like the "healing dispenser only heals for 1 health at a time" bug has returned

i am sure i am on the newest version since i have the new c4 settings available in the f1 menu

**Comment by wgetJane** [comment]
> on this version of waterworld the button inside the soda machien that is supposed to teleport you does not work

it doesn't work in base ttt either, the button is locked

using the `ent_fire !picker unlock` console command, the button can be pressed in both ttt and ttt2

> also, it seems like the "healing dispenser only heals for 1 health at a time" bug has returned

this might be caused by the `ENT.CanUseKey = true` line in ttt_health_station.lua, which is not present in base ttt

**Comment by Crashington** [comment]
oh sorry on the waterworld thing then. weird that its locked but thats irrelevant here then.

**Comment by TimGoll** [comment]
The health station issue is handled in TTT2. Maybe you accidentally removed our continuous use implementation?

**Comment by Crashington** [comment]
i wouldnt know how i would have done that. we use the normal workshop version on the server. unless another addon could be somehow interfering? we dont have anything that directly interacts with the health station anyway

**Comment by wgetJane** [comment]
probably meant me, not you, though i haven't touched the health station at all, just forgot to test it for this pr

i'll figure out a solution later, was my fault anyway for not checking the health station (i just tested the traitor's placeables lmao)

**Comment by TimGoll** [comment]
> probably meant me, not you, though i haven't touched the health station at all, just forgot to test it for this pr

It is not part of the health station per se, but part of the use code. Holding E retriggers use 10 times per second.

In theory this is an engine feature. I reimplemented it in lua. Dunno which approach would be best with your changes though
