### PR TITLE
detective search results not be overwritten

### LINKED ISSUE #1359: Bodysearch: Local results overwrite policing results in the scoreboard
## Your version of TTT2 (mandatory)

Leave one of the following:

- Latest GitHub version

## Describe the bug (mandatory)

corpses don't get marked as detective peeped

## To reproduce

1. Begin a round as an innocent.
2. Have a player kill another player.
3. Have any non-detective, non-you player check the body with instant-confirm enabled.
4. The corpse will display as confirmed.
5. Have a detective inspect the confirmed corpse.
6. The corpse will not show the "This body has been inspected by a public policing role" targetid info.
7. The scoreboard row for that corpse will not have been updated to show the magnifying glass to display corpse information.

## Expected behaviour

- The corpse shows the blue flare.
- The scoreboard is adequately updated.

## Context (please provide as much as you can)

- This might be mitigated by #1260, idk.
- If you **are** a detective, you will always observe this as functioning correctly -- because local search results still preside over publicly available knowledge. You must remain an innocent to see this occur.

### PR DESCRIPTION
**Pull request by EntranceJew**
fixes #1359

https://github.com/TTT-2/TTT2/assets/5711436/2addb0ac-9b65-468b-bb23-04019f592adf

### CODE REVIEW

File: lua/ttt2/libraries/bodysearch.lua [hunk 1]
```diff
@@ -997,62 +997,61 @@ if CLIENT then
     -- @param SceneData sceneData The table of scene data that should be stored
```
Comment (saibotk) [inline lua/ttt2/libraries/bodysearch.lua:997]:
```suggestion
    -- @param SceneData newData The table of scene data that should be stored
```

**Review by saibotk — APPROVED** [review]
Seems good, but ofc @TimGoll needs to check this

File: lua/ttt2/libraries/bodysearch.lua [hunk 2]
```diff
@@ -994,65 +994,64 @@ if CLIENT then
...
         -- entries
-        local newData = ply.bodySearchResult or {}
-        table.Merge(newData, sceneData)
+        table.Merge(oldData, newData)
 
-        -- keep the original finder info if previously searched by public policing role
-        newData.base = previousSceneDataBase or newData.base
+        if previousOldDataBase then
+            oldData.base = previousOldDataBase or oldData.base
+        end
```
Comment (TimGoll) [inline lua/ttt2/libraries/bodysearch.lua:1033]:
```suggestion
        oldData.base = previousOldDataBase or oldData.base
```

**Review by TimGoll — APPROVED** [review]
